name: Build and Test api-gateway Maven Project

on:
  push:
    paths:
      - 'api-gatway/**'  # Adjust this path to match the location of your project
    branches: [ "main" ]     
  pull_request:
    paths:
      - 'api-gatway/**'  # Adjust this path to match the location of your project
    branches: [ "main" ]    

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api-gatway

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
       
    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: check current folder windows
      run: dir  
      
    - name: Login to docker hub
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
    - name: Build docker image
      run: docker build -t ghailenem/mmv2-api-gatway:0.0.1-SNAPSHOT .
    - name: Check docker image
      run: docker images
    - name: Tag docker image
      run: docker tag ghailenem/mmv2-api-gatway:0.0.1-SNAPSHOT ghailenem/mmv2-api-gatway:0.0.1-SNAPSHOT
    - name: Publish image to docker hub
      run: docker push ghailenem/mmv2-api-gatway:0.0.1-SNAPSHOT
        
    - name: Log out from Docker Hub
      run: docker logout
    
# Add additional steps here for deployment or other actions.
