name: Build and Test currency-exchange Maven Project

on:
  push:
    paths:
      - 'currency-exchange-service/**'  # Adjust this path to match the location of your project
    branches: [ "main" ]     
  pull_request:
    paths:
      - 'currency-exchange-service/**'  # Adjust this path to match the location of your project
    branches: [ "main" ]    

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./currency-exchange-service

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    #- name: Build with Maven
    #  run: mvn -f currency-exchange-service/pom.xml clean install -DskipTests

    #- name: Run Tests
     # run: mvn -f currency-exchange-service/pom.xml test
    #- name: Build and Create Docker Image
     # run: mvn -f currency-exchange-service/ spring-boot:build-image -DskipTests  
      
     #    docker logout
    - name: check current folder windows
      run: dir  
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}  

    - name: Login to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v4      
      with:
        image: ghailene/mmv2-currency-exchange-service
        tag: 0.0.1-SNAPSHOT
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}         
    
   # - name: Push Docker image to Docker Hub
    #  run: mvn -f currency-exchange-service/ clean install -DskipTests
    
   # - name: Build docker image
   #   run: docker build -t ghailene/mmv2-${PROJECT_ARTIFACT_ID}:${PROJECT_VERSION}
      

    #    docker logout
    - name: Log out from Docker Hub
      run: docker logout
    
# Add additional steps here for deployment or other actions.
