name: Build and Test currency-exchange Maven Project

on:
  push:
    paths:
      - 'currency-exchange-service/**'  # Adjust this path to match the location of your project
    branches: [ "main" ]     
  pull_request:
    paths:
      - 'currency-exchange-service/**'  # Adjust this path to match the location of your project
    branches: [ "main" ]    

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -f currency-exchange-service/pom.xml clean install

    - name: Run Tests
      run: mvn -f currency-exchange-service/pom.xml test

# Add additional steps here for deployment or other actions.
